 version: '3.8'
 services: 
  sql-server:
    container_name: sql-server
    image: mcr.microsoft.com/mssql/server
    ports:
      - "1433:1433"
    environment:
      SA_PASSWORD: MiContraseniaN5
      ACCEPT_EULA: Y
  db-init:
    image: mcr.microsoft.com/mssql/server
    network_mode: service:sql-server
    volumes:
      - ./scripts:/scripts
    command: bash -c 'until /opt/mssql-tools/bin/sqlcmd -U sa -P MiContraseniaN5 -d master -i /scripts/init.sql; do echo retry && sleep 5; done'
    depends_on:
      - sql-server
  elasticsearch:
    container_name: elasticsearch
    image: docker.elastic.co/elasticsearch/elasticsearch:7.17.5
    environment:
      - discovery.type=single-node
    ports:
      - "9200:9200"
      - "9300:9300"
    depends_on:
     - sql-server 
  web-app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8080:7203"
    depends_on:
      - elasticsearch
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=http://+:7203