 version: '3.8'
 services: 
  sql-server:
    container_name: sql-server
    image: mcr.microsoft.com/mssql/server
    ports:
      - "1433:1433"
    environment:
      SA_PASSWORD: MiContraseniaN5
      ACCEPT_EULA: Y
    volumes:
      - ./scripts:/scripts
  elasticsearch:
    container_name: elasticsearch
    image: docker.elastic.co/elasticsearch/elasticsearch:7.17.5
    environment:
      - discovery.type=single-node
    ports:
      - "9200:9200"
      - "9300:9300"
  web-app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8080:7203"
    depends_on:
      - sql-server 
      - elasticsearch
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=http://+:7203